// Daftar tamu — akses via ?to=slug
// Contoh: https://user.github.io/repo/?to=fahmi
const GUESTS = {
  // ── IDM ──────────────────────────────────────────────
  'fahmi-idm'  : { name: 'Fahmi',       group: 'IDM'  },
  'sella'      : { name: 'Sella',       group: 'IDM'  },
  'fikri'      : { name: 'Fikri',       group: 'IDM'  },
  'dimas'      : { name: 'Dimas',       group: 'IDM'  },
  'alvin-idm'  : { name: 'Alvin',       group: 'IDM'  },
  'ana'        : { name: 'Ana',         group: 'IDM'  },
  'bunga'      : { name: 'Bunga',       group: 'IDM'  },
  'rohman'     : { name: 'Rohman',      group: 'IDM'  },
  'layli'      : { name: 'Layli',       group: 'IDM'  },
  'bondan-idm' : { name: 'Bondan',      group: 'IDM'  },
  'desy'       : { name: 'Desy',        group: 'IDM'  },
  'kiki'       : { name: 'Kiki',        group: 'IDM'  },
  'bu-dian'    : { name: 'Bu Dian',     group: 'IDM'  },
  'rival'      : { name: 'Rival',       group: 'IDM'  },
  'olga'       : { name: 'Olga',        group: 'IDM'  },
  'septi-idm'  : { name: 'Septi',       group: 'IDM'  },
  'giani'      : { name: 'Giani',       group: 'IDM'  },
  'bu-agnes'   : { name: 'Bu Agnes',    group: 'IDM'  },
  'nabila'     : { name: 'Nabila',      group: 'IDM'  },
  'pak-syafii' : { name: "Pak Syafi'i", group: 'IDM'  },
  'irva'       : { name: 'Irva',        group: 'IDM'  },
  'khusnul'    : { name: 'Khusnul',     group: 'IDM'  },
  'rizal'      : { name: 'Rizal',       group: 'IDM'  },
  'gladies'    : { name: 'Gladies',     group: 'IDM'  },
  'fandy'      : { name: 'Fandy',       group: 'IDM'  },
  'dian-idm'   : { name: 'Dian',        group: 'IDM'  },
  'adi'        : { name: 'Adi',         group: 'IDM'  },
  'pak-kus'    : { name: 'Pak Kus',     group: 'IDM'  },
  'gilang'     : { name: 'Gilang',      group: 'IDM'  },
  'lami'       : { name: 'Lami',        group: 'IDM'  },
  'sena'       : { name: 'Sena',        group: 'IDM'  },
  'pak-ponco'  : { name: 'Pak Ponco',   group: 'IDM'  },
  'novi'       : { name: 'Novi',        group: 'IDM'  },
  'pak-satrio' : { name: 'Pak Satrio',  group: 'IDM'  },
  'riska'      : { name: 'Riska',       group: 'IDM'  },
  'arina'      : { name: 'Arina',       group: 'IDM'  },
  'rangga'     : { name: 'Rangga',      group: 'IDM'  },
  // ── Umum ─────────────────────────────────────────────
  'vika'       : { name: 'Vika',        group: 'Umum' },
  'rofia'      : { name: 'Rofia',       group: 'Umum' },
  'hajeng'     : { name: 'Hajeng',      group: 'Umum' },
  'afifah'     : { name: 'Afifah',      group: 'Umum' },
  'amel'       : { name: 'Amel',        group: 'Umum' },
  'sintya'     : { name: 'Sintya',      group: 'Umum' },
  'april'      : { name: 'April',       group: 'Umum' },
  'chindy'     : { name: 'Chindy',      group: 'Umum' },
  'chandra'    : { name: 'Chandra',     group: 'Umum' },
  'dani'       : { name: 'Dani',        group: 'Umum' },
  'amitta'     : { name: 'Amitta',      group: 'Umum' },
  'nitta'      : { name: 'Nitta',       group: 'Umum' },
  'nadia'      : { name: 'Nadia',       group: 'Umum' },
  'dewi'       : { name: 'Dewi',        group: 'Umum' },
  'mozza'      : { name: 'Mozza',       group: 'Umum' },
  'dita'       : { name: 'Dita',        group: 'Umum' },
  'intan'      : { name: 'Intan',       group: 'Umum' },
  'larika'     : { name: 'Larika',      group: 'Umum' },
  'meysia'     : { name: 'Meysia',      group: 'Umum' },
  'septi'      : { name: 'Septi',       group: 'Umum' },
  'silvis'     : { name: 'Silvis',      group: 'Umum' },
  'hinta'      : { name: 'Hinta',       group: 'Umum' },
  'violeta'    : { name: 'Violeta',     group: 'Umum' },
  'arya'       : { name: 'Arya',        group: 'Umum' },
  'aria'       : { name: 'Aria',        group: 'Umum' },
  'diva'       : { name: 'Diva',        group: 'Umum' },
  'ahmad'      : { name: 'Ahmad',       group: 'Umum' },
  'david'      : { name: 'David',       group: 'Umum' },
  'dessya'     : { name: 'Dessya',      group: 'Umum' },
  'nabon'      : { name: 'Nabon',       group: 'Umum' },
  'farizz'     : { name: 'Farizz',      group: 'Umum' },
  'abel'       : { name: 'Abel',        group: 'Umum' },
  'alvin'      : { name: 'Alvin',       group: 'Umum' },
  'davit'      : { name: 'Davit',       group: 'Umum' },
  'davito'     : { name: 'Davito',      group: 'Umum' },
  'devita'     : { name: 'Devita',      group: 'Umum' },
  'varekha'    : { name: 'Varekha',     group: 'Umum' },
  'tata'       : { name: 'Tata',        group: 'Umum' },
  'wunia'      : { name: 'Wunia',       group: 'Umum' },
  'yusintya'   : { name: 'Yusintya',    group: 'Umum' },
  'ega'        : { name: 'Ega',         group: 'Umum' },
  'dian'       : { name: 'Dian',        group: 'Umum' },
  'bondan'     : { name: 'Bondan',      group: 'Umum' },
  'fahmi'      : { name: 'Fahmi',       group: 'Umum' },
};
